FROM n8nio/n8n:latest

ENV NODE_ENV=production
ENV N8N_BINARY_DATA_MODE=filesystem
ENV N8N_EXECUTIONS_TIMEOUT=0
ENV N8N_EXECUTIONS_TIMEOUT_MAX=0
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV N8N_PERSONALIZATION_ENABLED=false

# Hugging Face requires port 7860
ENV N8N_PORT=7860

EXPOSE 7860
